### ISSUE TITLE
Path Error when Trying to download a file

### ISSUE THREAD

**Issue by monzersmiledev** [monzersmiledev/sender-server#1]
this error shown when i try to download i file 

`E:\Projects\sender\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:363:5)
    at validateString (node:internal/validators:119:11)
    at resolve (node:path:167:9)
    at ServerResponse.download (E:\Projects\sender\node_modules\express\lib\response.js:570:18)
    at Query.<anonymous> (E:\Projects\sender\src\controlers\download.js:10:43)
    at Query.<anonymous> (E:\Projects\sender\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (E:\Projects\sender\node_modules\mysql\lib\Connection.js:488:16)
    at Query.Sequence.end (E:\Projects\sender\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (E:\Projects\sender\node_modules\mysql\lib\protocol\sequences\Query.js:149:8)
    at Query.EofPacket (E:\Projects\sender\node_modules\mysql\lib\protocol\sequences\Query.js:133:8) {
  code: 'ERR_INVALID_ARG_TYPE'
}`

I'll be working on it

**Comment by monzersmiledev** [comment]
the problem caused by database query result error

the results are unreadable for JavaScript so i had to stringfiy and parse it to be readable for js
also i changed the logic of createList module because it didn't show all the data come from the result
